### ISSUE TITLE
Question: why must the input length match the expected length?

### ISSUE THREAD

**Issue by wolfoo2931** [marcelklehr/changesets#17]
I'm wondering why the following code example is not considered to be correct:

```
var Changeset = require('changesets').Changeset;
str = 'Hans Peter';
cs = Changeset.create().retain(4).insert(' Jürgen').end();
cs.apply(str);
Error: Input length doesn't match expected length. expected: 4; actual: 10
```
I must retain the rest of the string to make it work:

`cs = Changeset.create().retain(4).insert(' Jürgen').retain(6).end();`

If I remove [the validation](https://github.com/marcelklehr/changesets/blob/master/lib/Changeset.js#L289) it works like expected. 

Is there a good reason for this validation?

Best Regards,
Oliver

**Comment by marcelklehr** [comment]
The reason is that if you want to use this library in a real world app, you will want it to fail early. I've seen lots of cases where etherpad would accept some actually broken changeset, and then errored later on because something didn't fit, even though the changeset being processed *at that time* was totally fine.

So, this is a precaution against a bug in an algorithm higher up the stack ;)
